{
 "title": "docker dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Broker Bytes in per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesinpersec",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics - Messages in per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesinpersec",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic bytes in per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesinpersec",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globaltopiccount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of offsets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "kafka_coordinator_group_groupmetadatamanager_numoffsets",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Requests per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_failedproducerequestspersec",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_produceridcount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "broker bytes in per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesinpersec",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "active broker count - docker ver",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}